export const ACTION_AUTHENTICATE = 'ACTION_AUTHENTICATE';
export const ACTION_AUTHENTICATE_SUCCESS = 'ACTION_AUTHENTICATE_SUCCESS';
export const ACTION_AUTHENTICATE_FAIL = 'ACTION_AUTHENTICATE_FAIL';

export const ACTION_SEARCH = 'ACTION_SEARCH';
export const ACTION_SEARCH_SUCCESS = 'ACTION_SEARCH_SUCCESS';
export const ACTION_SEARCH_FAIL = 'ACTION_SEARCH_FAIL';